// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250513215311_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Cidade", b =>
                {
                    b.Property<int>("id_cidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_cidade");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cidade"));

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("nm_cidade");

                    b.Property<int>("id_estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estado");

                    b.HasKey("id_cidade");

                    b.HasIndex("id_estado");

                    b.ToTable("t_gpsMottu_cidade", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Contato", b =>
                {
                    b.Property<int>("id_contato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_contato");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_contato"));

                    b.Property<int>("id_Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nmDono")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("nm_dono");

                    b.Property<int>("status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_contato");

                    b.HasIndex("id_Telefone")
                        .IsUnique();

                    b.ToTable("t_gpsMottu_contato", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Endereco", b =>
                {
                    b.Property<int>("id_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_endereco"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("cep");

                    b.Property<string>("NomeLogradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NumeroLogradouro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("numero");

                    b.Property<int>("id_cidade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_endereco");

                    b.HasIndex("id_cidade");

                    b.ToTable("t_gpsMottu_endereco", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Estado", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estado");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nm_estado");

                    b.Property<int>("id_pais")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_estado");

                    b.HasIndex("id_pais");

                    b.ToTable("t_gpsMottu_estado", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Filial", b =>
                {
                    b.Property<int>("id_filial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_filial"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("cnpj_filial");

                    b.Property<int>("id_contato")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_endereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("senha_filial");

                    b.HasKey("id_filial");

                    b.HasIndex("id_contato");

                    b.HasIndex("id_endereco");

                    b.ToTable("t_gpsMottu_filial", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Moto", b =>
                {
                    b.Property<int>("id_moto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_moto");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_moto"));

                    b.Property<string>("CondicaoMoto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("condicao_manutencao_moto");

                    b.Property<string>("IdentificadorMoto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("identificador_moto");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.Property<int>("id_filial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_tipo_moto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_moto");

                    b.HasIndex("id_filial");

                    b.HasIndex("id_tipo_moto");

                    b.ToTable("t_gpsMottu_moto", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Pais", b =>
                {
                    b.Property<int>("Id_pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pais"));

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_pais");

                    b.HasKey("Id_pais");

                    b.ToTable("t_gpsMottu_pais", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Perfil", b =>
                {
                    b.Property<int>("id_perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_perfil");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_perfil"));

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("nm_perfil");

                    b.HasKey("id_perfil");

                    b.ToTable("t_gpsMottu_perfil", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.SecoesFilial", b =>
                {
                    b.Property<int>("id_secao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_secao_filial");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_secao"));

                    b.Property<int>("Lado1")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Lado_1");

                    b.Property<int>("Lado2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Lado_2");

                    b.Property<int>("Lado3")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Lado_3");

                    b.Property<int>("Lado4")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Lado_4");

                    b.Property<int>("id_filial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_tipo_secao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_secao");

                    b.HasIndex("id_filial");

                    b.HasIndex("id_tipo_secao");

                    b.ToTable("t_gpsMottu_secoes_filial", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Telefone", b =>
                {
                    b.Property<int>("id_telefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_telefone");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_telefone"));

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("nr_ddd");

                    b.Property<string>("Ddi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("nr_ddi");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("nr_telefone");

                    b.HasKey("id_telefone");

                    b.ToTable("t_gpsMottu_telefone", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.TipoMoto", b =>
                {
                    b.Property<int>("id_tipo_moto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tipo_moto");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_moto"));

                    b.Property<string>("NomeTipoMoto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nm_tipo_moto");

                    b.HasKey("id_tipo_moto");

                    b.ToTable("t_gpsMottu_tipo_moto", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.TipoSecao", b =>
                {
                    b.Property<int>("id_tipo_secao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tipo_secao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_secao"));

                    b.Property<string>("NomeTipoSecao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nm_tipo_secao");

                    b.HasKey("id_tipo_secao");

                    b.ToTable("t_gpsMottu_tipo_secao", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_email");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_usuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ds_senha");

                    b.Property<int>("id_filial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_perfil")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_filial");

                    b.HasIndex("id_perfil");

                    b.ToTable("t_gpsMottu_usuario", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Uwb", b =>
                {
                    b.Property<int>("id_uwb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_uwb");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_uwb"));

                    b.Property<string>("ValorUwb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("vl_iwb");

                    b.Property<int>("id_moto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id_uwb");

                    b.HasIndex("id_moto");

                    b.ToTable("t_gpsMottu_uwb", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.Cidade", b =>
                {
                    b.HasOne("WebApplication3.Models.Estado", null)
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cidade_estado");
                });

            modelBuilder.Entity("WebApplication3.Models.Contato", b =>
                {
                    b.HasOne("WebApplication3.Models.Contato", null)
                        .WithOne()
                        .HasForeignKey("WebApplication3.Models.Contato", "id_Telefone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Contato_telefone_fk");
                });

            modelBuilder.Entity("WebApplication3.Models.Endereco", b =>
                {
                    b.HasOne("WebApplication3.Models.Cidade", null)
                        .WithMany()
                        .HasForeignKey("id_cidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cidade_endereco");
                });

            modelBuilder.Entity("WebApplication3.Models.Estado", b =>
                {
                    b.HasOne("WebApplication3.Models.Pais", null)
                        .WithMany()
                        .HasForeignKey("id_pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("estado_pais");
                });

            modelBuilder.Entity("WebApplication3.Models.Filial", b =>
                {
                    b.HasOne("WebApplication3.Models.Contato", null)
                        .WithMany()
                        .HasForeignKey("id_contato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contato_filial");

                    b.HasOne("WebApplication3.Models.Endereco", null)
                        .WithMany()
                        .HasForeignKey("id_endereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("filial_endereco");
                });

            modelBuilder.Entity("WebApplication3.Models.Moto", b =>
                {
                    b.HasOne("WebApplication3.Models.Filial", null)
                        .WithMany()
                        .HasForeignKey("id_filial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Moto_Filial");

                    b.HasOne("WebApplication3.Models.TipoMoto", null)
                        .WithMany()
                        .HasForeignKey("id_tipo_moto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Moto_TipoMoto");
                });

            modelBuilder.Entity("WebApplication3.Models.SecoesFilial", b =>
                {
                    b.HasOne("WebApplication3.Models.Filial", null)
                        .WithMany()
                        .HasForeignKey("id_filial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("secao_filial");

                    b.HasOne("WebApplication3.Models.TipoSecao", null)
                        .WithMany()
                        .HasForeignKey("id_tipo_secao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("secao_tipoSecao");
                });

            modelBuilder.Entity("WebApplication3.Models.Usuario", b =>
                {
                    b.HasOne("WebApplication3.Models.Filial", null)
                        .WithMany()
                        .HasForeignKey("id_filial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_filial");

                    b.HasOne("WebApplication3.Models.Perfil", null)
                        .WithMany()
                        .HasForeignKey("id_perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_perfil");
                });

            modelBuilder.Entity("WebApplication3.Models.Uwb", b =>
                {
                    b.HasOne("WebApplication3.Models.Moto", null)
                        .WithMany()
                        .HasForeignKey("id_moto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
